SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

PADDLE_X_OFFSET = 350
PADDLE_SPEED = 20
AI_SPEED = 4
PADDLE_HALF_HEIGHT = 50
PADDLE_LIMIT = SCREEN_HEIGHT // 2 - PADDLE_HALF_HEIGHT

BALL_SPEED_X = 4
BALL_SPEED_Y = 4
BALL_RADIUS = 10

FRAME_DELAY = 16

MODE_AI_AI = "ai_ai"
MODE_AI_PLAYER = "ai_player"
MODE_PLAYER_PLAYER = "player_player"

